sample_project/sample_app/urls.py
from django.urls import path
from django.conf.urls import include

from . import views


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),

    path('', views.IndexView.as_view(), name='index'),
    path('authors/', views.AuthorsView.as_view(), name='authors'),
    path('author/<int:pk>/', views.AuthorView.as_view(), name='author_by_id'),
    path('create_book/', views.CreateBookView.as_view(), name='create_book'),
    path('edit_book/<int:pk>/', views.EditBookView.as_view(), name='edit_book'),
    path('delete_book/<int:pk>', views.DeleteBookView.as_view(), name='delete_book'),
    path('favorites/', views.FavoritesView.as_view(), name='favorites'),
    path('add-to-favorites/', views.AddFavorite.as_view(), name='add_to_favorites'),
    path('remove-from-favorites/', views.RemoveFavorite.as_view(), name='remove_from_favorites'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('books/', views.BooksView.as_view(), name='books'),
]

sample_project/sample_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sample_app.urls'))
]

sample_project/sample_app/models.py
from django.db import models
from django.core.exceptions import ValidationError

def validate_even(value):
    if value % 2 != 0:
        raise ValidationError(
            '%(value)s is not an even number',
            params={'value': value},
        )


class Country(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_authors(self):
        pass


class Author(models.Model):
    name = models.CharField(max_length=255)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_country(self):
        pass

    def get_books(self):
        pass


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    isbn = models.CharField(max_length=255)
    popularity = models.DecimalField(
        max_digits=4, decimal_places=2, validators=[validate_even])

    def __str__(self):
        return "{}({})".format(self.title, self.author)

    def get_author(self):
        pass

sample_project/sample_app/forms.py
from django import forms

from django.contrib.auth.models import User
from .models import Country, Author, Book


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ['title', 'author', 'isbn', 'popularity']


class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username']

sample_project/sample_app/views.py
from datetime import datetime

from django.urls import reverse
from django.contrib.auth.models import User
from django.http import HttpResponseNotFound
from django.contrib.auth import authenticate, login
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, View, RedirectView
from django.contrib.auth.decorators import login_required, user_passes_test

from .models import Author, Book
from .forms import BookForm, SignUpForm


def is_staff(user):
    return user.is_staff


class IndexView(TemplateView):
    template_name = 'books.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Initialize the favorite_books variable in current session.
        self.request.session.setdefault('favorite_books', [])
        self.request.session.save()

        books = Book.objects.all()
        sort_method = self.request.GET.get('sort', 'asc')
        if sort_method == 'asc':
            books = books.order_by('popularity')
        elif sort_method == 'desc':
            books = books.order_by('-popularity')

        if 'q' in self.request.GET:
            q = self.request.GET['q']
            books = books.filter(title__icontains=q)

        context['books'] = books
        context['authors'] = Author.objects.all()
        context['sort_method'] = sort_method
        return context


class BooksView(RedirectView):
    url = '/'


@method_decorator(login_required, name='dispatch')
@method_decorator(user_passes_test(is_staff), name='dispatch')
class CreateBookView(TemplateView):
    template_name = 'create_book.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book_form'] = BookForm()
        return context

    def post(self, request, *args, **kwargs):
        book_form = BookForm(request.POST)
        if book_form.is_valid():
            book_form.save()
            return redirect('index')
        return render(
            request,
            'create_book.html',
            context={'book_form': book_form}
        )


@method_decorator(login_required, name='dispatch')
@method_decorator(user_passes_test(is_staff), name='dispatch')
class EditBookView(TemplateView):
    template_name = 'edit_book.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = get_object_or_404(Book, id=kwargs.get('book_id'))
        context['book'] = book
        context['book_form'] = BookForm(instance=book)
        return context

    def post(self, request, *args, **kwargs):
        book = get_object_or_404(Book, id=kwargs.get('book_id'))
        book_form = BookForm(request.POST, instance=book)
        if book_form.is_valid():
            book_form.save()
            return redirect('index')
        return render(
            request,
            'edit_book.html',
            context={
                'book': book,
                'book_form': book_form
            }
        )


@method_decorator(login_required, name='dispatch')
@method_decorator(user_passes_test(is_staff), name='dispatch')
class DeleteBookView(View):

    def post(self, request, *args, **kwargs):
        book_id = request.POST.get('book_id')
        book = get_object_or_404(Book, id=book_id)
        book.delete()
        return redirect('/')


class AuthorsView(TemplateView):
    template_name = 'authors.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authors'] = Author.objects.all()
        return context


class AuthorView(TemplateView):
    template_name = 'author.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = get_object_or_404(Author, id=kwargs.get('author_id'))
        context['author'] = author
        return context


class FavoritesView(TemplateView):
    template_name = 'favorites.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        books_ids = self.request.session.get('favorite_books', [])
        favorite_books = Book.objects.filter(id__in=books_ids)
        context['favorite_books'] = favorite_books
        return context


class AddFavorite(View):

    def post(self, request, *args, **kwargs):
        request.session.setdefault('favorite_books', [])
        request.session['favorite_books'].append(request.POST.get('book_id'))
        request.session.save()
        return redirect('index')


class RemoveFavorite(View):

    def post(self, request, *args, **kwargs):
        if request.session.get('favorite_books'):
            request.session['favorite_books'].remove(request.POST.get('book_id'))
            request.session.save()
        return redirect('index')


class SignUpView(TemplateView):
    template_name = 'signup.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['signup_form'] = SignUpForm()
        return context

    def post(self, request, *args, **kwargs):
        signup_form = SignUpForm(request.POST)
        if signup_form.is_valid():
            user = User.objects.create(username=request.POST['username'])
            user.set_password(request.POST['password'])
            user.save()
            login(request, user)
            return redirect('index')
        return render(
            request,
            'signup.html',
            context={'signup_form': signup_form}
        )

sample_project/sample_app/templates/author.html
{% extends "base.html" %}

{% block main %}
  <p class="h1">Welcome to our Library!</p>
  <div class="lead">
    <p>You're browsing our Author <strong>{{ object.name }}</strong> (born in {{ object.country.name }}):</p>
    <p>Our collection includes:</p>
    <ul>
      {% for book in object.book_set.all %}
      <li>{{ book.title }} ({{ book.popularity }})</li>
      {% endfor %}
    </ul>
  </div>
  <a href="/authors"><button type="button" class="btn btn-outline-primary">← Back</button></a>
{% endblock %}

sample_project/sample_app/templates/authors.html
{% extends "base.html" %}

{% block main %}
  <p class="h1">Welcome to our Library!</p>
  <p class="lead">These are our selected authors:</p>
  <table class="table table-bordered table-hover text-center lead">
    <thead>
      <tr>
        <th>#</th>
        <th>Author Name</th>
        <th>Country</th>
      </tr>
    </thead>
    <tbody>
      {% for author in object_list %}
        <tr>
          <td>{{ author.id }}</td>
          <td><a href="{% url 'author_by_id' author.id %}">{{ author.name}}</a></td>
          <td>{{ author.country.name}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
  <a href="/"><button type="button" class="btn btn-outline-primary">← Back</button></a>
{% endblock %}

sample_project/sample_app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <title>Our library</title>

    <style media="screen">
      .container {
        margin-top: 80px;
      }

      a {
        color: black;
      }

      .nav-item {
        margin-right: 5px;
      }
    </style>
  </head>
  <body class="container">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/"><img src="https://rmotr.com/static/favicons/apple-icon-60x60.c69b596ccabe.png" alt="" width="32"></a>
      <ul class="nav navbar-nav mr-auto"></ul>
      <ul class="nav navbar-nav">
      {% if request.user.is_authenticated %}
        <li class="nav-item"><a class="nav-link active" href="#"><i class="fa fa-user"></i> {{request.user.username|capfirst}}</a></li>
        <li class="nav-item"><a class="btn btn-outline-light" href="/accounts/logout">Log out</a></li>
      {% else %}
        <li class="nav-item"><a class="btn btn-outline-light" href="/accounts/login">Log in</a></li>
        <li class="nav-item"><a class="btn btn-outline-light" href="/signup">Sign up</a></li>
      {% endif %}
      </ul>
    </nav>


    {% block main %}
    {% endblock %}
  </body>
</html>

sample_project/sample_app/templates/books.html
{% extends "base.html" %}

{% block main %}
  <p class="h1">Welcome to our Library!</p>
  <p class="lead">These are our best books:</p>
  <form action="" method="GET">
    <div class="row">
      <div class="col-4">
        <input type="text" name="q" class="form-control">
      </div>
      <div class="col-1">
        <input type="submit" class="btn btn-primary btn-xs" value="Search">
      </div>
      <div class="col-7">
        {% if request.user.is_authenticated %}
          <a href="/favorites" class="btn btn-outline-warning btn-xs float-right">→ Go to Favorites ({{request.session.favorite_books|length}})</a>
        {% endif %}
      </div>
    </div>
  </form>
  <br>
  <table class="table table-bordered table-hover text-center lead">
    <thead>
      <tr>
        <th>#</th>
        <th>Book Title</th>
        <th>Author</th>
        <th><a href="/?sort={% if sort_method == 'asc' %}desc{% else %}asc{% endif %}">Popularity ({% if sort_method == 'asc' %}↓{% else %}↑{% endif %})</a></th>
        {% if request.user.is_authenticated %}
          <th>Favorite</th>
          {% if request.user.is_staff %}
            <th>Actions</th>
          {% endif %}
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for book in books %}
        <tr>
          <td class="align-middle">{{ book.id }}</td>
          <td class="align-middle">{{ book.title}}</td>
          <td class="align-middle"><a href="{% url 'author_by_id' book.author.id %}">{{ book.author.name}}</a></td>
          <td class="align-middle">{{ book.popularity}}</td>
          {% if request.user.is_authenticated %}
            <td>
              {% if book.id|slugify not in request.session.favorite_books %}
                <form action="{% url 'add_to_favorites' %}" method='post' class='inline'>
                  {% csrf_token %}
                  <button class="btn btn-outline-warning btn-xs far fa-star disabled" type="submit" name="add_to_favorites"></button>
                  <input type="hidden" name="book_id" value="{{book.id}}">
                </form>
              {% else %}
                <form action="{% url 'remove_from_favorites' %}" method='post' class='inline'>
                  {% csrf_token %}
                  <button class="btn btn-warning btn-xs far fa-star" type="submit" name="remove_from_favorites"></button>
                  <input type="hidden" name="book_id" value="{{book.id}}">
                </form>
              {% endif %}
            </td>
          {% endif %}

          {% if request.user.is_authenticated and request.user.is_staff %}
            <td class="align-middle">
              <div class="row justify-content-md-center">
                <a href="/edit_book/{{book.id}}" style="margin-right: 5px;"><button type="button" class="btn btn-outline-warning btn-xs">Edit</button></a>
                <form class="" action="/delete_book/{{book.id}}" method="post">
                  {% csrf_token %}
                  <input type="hidden" name='book_id' value='{{book.id}}'>
                  <input type="submit" value='Delete' class="btn btn-outline-danger btn-xs">
                </form>
              </div>
            </td>
          {% endif %}

        </tr>
      {% endfor %}
    </tbody>
  </table>
  <p class="lead"><a href="{% url 'authors' %}">Prefer to browse by author?</a></p>

  {% if request.user.is_authenticated and request.user.is_staff %}
    <a href="/create_book/"><button type="button" class="btn btn-info">Create Book</button></a>
  {% endif %}
{% endblock %}

sample_project/sample_app/templates/create_book.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block main %}
  <form action="/create_book/" method="POST">
    <p class="h3">Create Book:</p>
    {% csrf_token %}
    {{form|crispy}}
    <a href="/"><button type="button" class="btn btn-outline-primary">← Back</button></a>
    <input type="submit" value="Create" class="btn btn-primary">
  </form>
{% endblock %}

sample_project/sample_app/templates/edit_book.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block main %}
  <form action="/edit_book/{{form.instance.id}}/" method="POST">
    <p class="h3">Edit Book:</p>
    {% csrf_token %}
    {{form|crispy}}
    <a href="/"><button type="button" class="btn btn-outline-primary">← Back</button></a>
    <input type="submit" value="Edit" class="btn btn-primary">
  </form>
{% endblock %}

sample_project/sample_app/templates/favorites.html
{% extends "base.html" %}

{% block main %}
  <div>
    <p class="lead">List of Favorite books:</p>
    {% if favorite_books %}
      <div>
        <table class="table table-bordered table-hover text-center lead">
          <thead>
            <tr>
              <th>#</th>
              <th>Book Title</th>
              <th>Author</th>
              <th>Popularity</th>
            </tr>
          </thead>
          <tbody>
            {% for book in favorite_books %}
              <tr>
                <td class="align-middle">{{ book.id }}</td>
                <td class="align-middle">{{ book.title}}</td>
                <td class="align-middle"><a href="{% url 'author_by_id' book.author.id %}">{{ book.author.name}}</a></td>
                <td class="align-middle">{{ book.popularity}}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <div>
        <p class="text-center font-italic lead">You didn't mark any book as favorite yet.</p>
      </div>
    {% endif %}
    <div>
      <a href="/"><button type="button" class="btn btn-outline-primary">← Back</button></a>
    </div>
  </div>
{% endblock %}

sample_project/sample_app/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block main %}
  <form action="/signup/" method="POST">
    <p class="h3">Signup:</p>
    {% csrf_token %}
    {{signup_form|crispy}}
    <a href="/"><button type="button" class="btn btn-outline-primary">← Back</button></a>
    <input type="submit" value="Create" class="btn btn-primary">
  </form>
{% endblock %}